-- ==========================================
-- Retail Sales Analysis
-- 02 - Basic Exploratory Data Analysis (EDA)
-- ==========================================

-- Business Question 1:
-- What is the total sales generated by the company?

SELECT ROUND(SUM(sales),2) AS Total_Sales
FROM orders;

-- Business Insight:
-- The company generated total sales of 2,326,534.35 during the analysis period.


-- Business Question 2:
-- What is the total profit earned by the company?

SELECT ROUND(SUM(profit),2) AS Total_Profit
FROM orders;

-- Business Insight:
-- The company earned a total profit of 292,296.81 during the analysis period.


-- Business Question 3:
-- How many unique orders were placed?

SELECT COUNT(DISTINCT order_id) AS Total_Orders
FROM orders;

-- Business Insight:
-- A total of 5,111 unique orders were placed during the analysis period.



-- Business Question 4:
-- How many unique customers placed orders?

SELECT COUNT(DISTINCT customer_id) AS Unique_Customers
FROM orders;

-- Business Insight:
-- A total of 804 unique customers placed orders during the analysis period.




-- Business Question 5:
-- What is the average sales per order?

SELECT ROUND(SUM(sales) / COUNT(DISTINCT order_id),2) AS Avg_Order_Value
FROM orders;

-- Business Insight:
-- On average, each customer order generated revenue of 455.20.


-- Business Question 6:
-- Which product category generated the highest sales?

SELECT category,
       ROUND(SUM(sales),2) AS Total_Sales
FROM orders
GROUP BY category
ORDER BY Total_Sales DESC
LIMIT 1;

-- Business Insight:
-- Technology generated the highest sales (839,893.28), making it the company's strongest revenue-generating category.



-- Business Question 7:
-- Which product category generated the highest profit?

SELECT category,
       ROUND(SUM(profit),2) AS Total_Profit
FROM orders
GROUP BY category
ORDER BY Total_Profit DESC
LIMIT 1;

-- Business Insight:
-- Technology is the most profitable product category, generating a total profit of 146,543.38.


-- Business Question 8:
-- Show total sales for each product category.

SELECT category,
       ROUND(SUM(sales),2) AS Total_Sales
FROM orders
GROUP BY category
ORDER BY Total_Sales DESC;

-- Business Insight:
-- Technology generated the highest sales, followed by Furniture and Office Supplies.



-- Business Question 9:
-- Show total sales and total profit for each product category.

SELECT category,
       ROUND(SUM(sales),2) AS Total_Sales,
       ROUND(SUM(profit),2) AS Total_Profit
FROM orders
GROUP BY category
ORDER BY Total_Sales DESC;

-- Business Insight:
-- Technology leads both sales and profit. Although Furniture has higher sales than Office Supplies, it generates much lower profit.


-- Business Question 10:
-- Which product category has the highest average discount?

SELECT category,
       ROUND(AVG(discount),2) AS Average_Discount
FROM orders
GROUP BY category
ORDER BY Average_Discount DESC
LIMIT 1;

-- Business Insight:
-- Office Supplies has the highest average discount among all product categories.
-- This suggests discounts may be used more frequently in this category to drive sales.


-- Business Question 11:
-- Which sub-category generated the highest sales?

SELECT sub_category,
       ROUND(SUM(sales),2) AS Total_Sales
FROM orders
GROUP BY sub_category
ORDER BY Total_Sales DESC
LIMIT 1;

-- Business Insight:
-- Chairs is the highest revenue-generating sub-category, contributing total sales of 335,768.25.



-- Business Question 12:
-- Which sub-category generated the highest profit?

SELECT sub_category,
       ROUND(SUM(profit),2) AS Total_Profit
FROM orders
GROUP BY sub_category
ORDER BY Total_Profit DESC
LIMIT 1;

-- Business Insight:
-- Copiers is the most profitable sub-category, generating a total profit of 56,093.94.


-- Business Question 13:
-- Which sub-category generated the lowest profit?

SELECT sub_category,
       ROUND(SUM(profit),2) AS Total_Profit
FROM orders
GROUP BY sub_category
ORDER BY Total_Profit ASC
LIMIT 1;

-- Business Insight:
-- Tables is the least profitable sub-category, with a total loss of 17,753.21.
-- This indicates that the business should investigate pricing, discounts, costs, and returns related to this sub-category.


-- Business Question 14:
-- Show the Top 10 Products by Total Sales.

SELECT product_name,
       ROUND(SUM(sales),2) AS Total_Sales
FROM orders
GROUP BY product_name
ORDER BY Total_Sales DESC
LIMIT 10;

-- Business Insight:
-- High-value office equipment and technology products dominate the top-selling products.
-- Products such as Canon imageCLASS 2200 Advanced Copier and Cisco TelePresence System
-- contribute significantly to overall sales.



-- Business Question 15:
-- Show the Top 10 Products by Total Profit.

SELECT product_name,
       ROUND(SUM(profit),2) AS Total_Profit
FROM orders
GROUP BY product_name
ORDER BY Total_Profit DESC
LIMIT 10;

-- Business Insight:
-- High-end technology products, especially copiers and printers, generate the highest profits.
-- The Canon imageCLASS 2200 Advanced Copier is the most profitable product, contributing 25,199.93 in total profit.


-- Business Question 16:
-- Show the Top 10 Loss-Making Products.

SELECT product_name,
       ROUND(SUM(profit),2) AS Total_Profit
FROM orders
GROUP BY product_name
ORDER BY Total_Profit ASC
LIMIT 10;

-- Business Insight:
-- These products generate the highest losses for the company.
-- Management should investigate pricing, discount policies, return rates, and procurement costs for these products to improve profitability.