-- ==========================================
-- Retail Sales Analysis
-- 02 - Basic Exploratory Data Analysis (EDA)
-- ==========================================

-- Business Question 1:
-- What is the total sales generated by the company?

SELECT ROUND(SUM(sales),2) AS Total_Sales
FROM orders;

-- Business Insight:
-- The company generated total sales of 2,326,534.35 during the analysis period.


-- Business Question 2:
-- What is the total profit earned by the company?

SELECT ROUND(SUM(profit),2) AS Total_Profit
FROM orders;

-- Business Insight:
-- The company earned a total profit of 292,296.81 during the analysis period.


-- Business Question 3:
-- How many unique orders were placed?

SELECT COUNT(DISTINCT order_id) AS Total_Orders
FROM orders;

-- Business Insight:
-- A total of 5,111 unique orders were placed during the analysis period.



-- Business Question 4:
-- How many unique customers placed orders?

SELECT COUNT(DISTINCT customer_id) AS Unique_Customers
FROM orders;

-- Business Insight:
-- A total of 804 unique customers placed orders during the analysis period.




-- Business Question 5:
-- What is the average sales per order?

SELECT ROUND(SUM(sales) / COUNT(DISTINCT order_id),2) AS Avg_Order_Value
FROM orders;

-- Business Insight:
-- On average, each customer order generated revenue of 455.20.


-- Business Question 6:
-- Which product category generated the highest sales?

SELECT category,
       ROUND(SUM(sales),2) AS Total_Sales
FROM orders
GROUP BY category
ORDER BY Total_Sales DESC
LIMIT 1;

-- Business Insight:
-- Technology generated the highest sales (839,893.28), making it the company's strongest revenue-generating category.



-- Business Question 7:
-- Which product category generated the highest profit?

SELECT category,
       ROUND(SUM(profit),2) AS Total_Profit
FROM orders
GROUP BY category
ORDER BY Total_Profit DESC
LIMIT 1;

-- Business Insight:
-- Technology is the most profitable product category, generating a total profit of 146,543.38.


-- Business Question 8:
-- Show total sales for each product category.

SELECT category,
       ROUND(SUM(sales),2) AS Total_Sales
FROM orders
GROUP BY category
ORDER BY Total_Sales DESC;

-- Business Insight:
-- Technology generated the highest sales, followed by Furniture and Office Supplies.



-- Business Question 9:
-- Show total sales and total profit for each product category.

SELECT category,
       ROUND(SUM(sales),2) AS Total_Sales,
       ROUND(SUM(profit),2) AS Total_Profit
FROM orders
GROUP BY category
ORDER BY Total_Sales DESC;

-- Business Insight:
-- Technology leads both sales and profit. Although Furniture has higher sales than Office Supplies, it generates much lower profit.


-- Business Question 10:
-- Which product category has the highest average discount?

SELECT category,
       ROUND(AVG(discount),2) AS Average_Discount
FROM orders
GROUP BY category
ORDER BY Average_Discount DESC
LIMIT 1;

-- Business Insight:
-- Office Supplies has the highest average discount among all product categories.
-- This suggests discounts may be used more frequently in this category to drive sales.


-- Business Question 11:
-- Which sub-category generated the highest sales?

SELECT sub_category,
       ROUND(SUM(sales),2) AS Total_Sales
FROM orders
GROUP BY sub_category
ORDER BY Total_Sales DESC
LIMIT 1;

-- Business Insight:
-- Chairs is the highest revenue-generating sub-category, contributing total sales of 335,768.25.



-- Business Question 12:
-- Which sub-category generated the highest profit?

SELECT sub_category,
       ROUND(SUM(profit),2) AS Total_Profit
FROM orders
GROUP BY sub_category
ORDER BY Total_Profit DESC
LIMIT 1;

-- Business Insight:
-- Copiers is the most profitable sub-category, generating a total profit of 56,093.94.


-- Business Question 13:
-- Which sub-category generated the lowest profit?

SELECT sub_category,
       ROUND(SUM(profit),2) AS Total_Profit
FROM orders
GROUP BY sub_category
ORDER BY Total_Profit ASC
LIMIT 1;

-- Business Insight:
-- Tables is the least profitable sub-category, with a total loss of 17,753.21.
-- This indicates that the business should investigate pricing, discounts, costs, and returns related to this sub-category.


-- Business Question 14:
-- Show the Top 10 Products by Total Sales.

SELECT product_name,
       ROUND(SUM(sales),2) AS Total_Sales
FROM orders
GROUP BY product_name
ORDER BY Total_Sales DESC
LIMIT 10;

-- Business Insight:
-- High-value office equipment and technology products dominate the top-selling products.
-- Products such as Canon imageCLASS 2200 Advanced Copier and Cisco TelePresence System
-- contribute significantly to overall sales.



-- Business Question 15:
-- Show the Top 10 Products by Total Profit.

SELECT product_name,
       ROUND(SUM(profit),2) AS Total_Profit
FROM orders
GROUP BY product_name
ORDER BY Total_Profit DESC
LIMIT 10;

-- Business Insight:
-- High-end technology products, especially copiers and printers, generate the highest profits.
-- The Canon imageCLASS 2200 Advanced Copier is the most profitable product, contributing 25,199.93 in total profit.


-- Business Question 16:
-- Show the Top 10 Loss-Making Products.

SELECT product_name,
       ROUND(SUM(profit),2) AS Total_Profit
FROM orders
GROUP BY product_name
ORDER BY Total_Profit ASC
LIMIT 10;

-- Business Insight:
-- These products generate the highest losses for the company.
-- Management should investigate pricing, discount policies, return rates, and procurement costs for these products to improve profitability.


-- Business Question 17:
-- Which region generated the highest sales?

SELECT region,
       ROUND(SUM(sales),2) AS Total_Sales
FROM orders
GROUP BY region
ORDER BY Total_Sales DESC
LIMIT 1;

-- Business Insight:
-- The West region generated the highest sales, contributing 739,813.61 in total revenue.
-- This indicates strong customer demand and sales performance in the West region.


-- Business Question 18:
-- Which region generated the highest profit?

SELECT region,
       ROUND(SUM(profit),2) AS Total_Profit
FROM orders
GROUP BY region
ORDER BY Total_Profit DESC
LIMIT 1;

-- Business Insight:
-- The West region generated the highest profit, contributing 110,798.82 in total profit.
-- This indicates that the region is not only the highest revenue generator but also the most profitable.


-- Business Question 19:
-- Which state generated the highest sales?

SELECT state_province,
       ROUND(SUM(sales),2) AS Total_Sales
FROM orders
GROUP BY state_province
ORDER BY Total_Sales DESC
LIMIT 1;

-- Business Insight:
-- California generated the highest sales, contributing 457,687.63 in total revenue.
-- This suggests California is the company's strongest-performing state by sales.


-- Business Question 20:
-- Which state generated the highest profit?

SELECT state_province,
       ROUND(SUM(profit),2) AS Total_Profit
FROM orders
GROUP BY state_province
ORDER BY Total_Profit DESC
LIMIT 1;

-- Business Insight:
-- California generated the highest profit, contributing 76,381.39 in total profit.
-- Along with leading in sales, California is also the most profitable state in the dataset.


-- Business Question 21:
-- Show the Top 10 Cities by Total Sales.

SELECT city,
       ROUND(SUM(sales),2) AS Total_Sales
FROM orders
GROUP BY city
ORDER BY Total_Sales DESC
LIMIT 10;

-- Business Insight:
-- New York City is the highest revenue-generating city.
-- The Top 10 cities contribute significantly to the company's overall sales, indicating key metropolitan markets drive business performance.




-- Business Question 22:
-- Show the Top 10 Cities by Total Profit.

SELECT city,
       ROUND(SUM(profit),2) AS Total_Profit
FROM orders
GROUP BY city
ORDER BY Total_Profit DESC
LIMIT 10;

-- Business Insight:
-- New York City is the most profitable city, generating a total profit of 62,036.98.
-- Los Angeles and Seattle also contribute significantly to the company's profitability,
-- indicating that major metropolitan areas are key profit centers.





-- Business Question 23:
-- Show the Top 10 Customers by Total Sales.

SELECT customer_id,
       customer_name,
       ROUND(SUM(sales),2) AS Total_Sales
FROM orders
GROUP BY customer_id, customer_name
ORDER BY Total_Sales DESC
LIMIT 10;

-- Business Insight:
-- Sean Miller is the highest revenue-generating customer with total purchases of 25,043.05.
-- The Top 10 customers contribute significantly to overall sales, highlighting the importance of retaining high-value customers.


-- Business Question 24:
-- Show the Top 10 Customers by Total Profit.

SELECT customer_id,
       customer_name,
       ROUND(SUM(profit),2) AS Total_Profit
FROM orders
GROUP BY customer_id, customer_name
ORDER BY Total_Profit DESC
LIMIT 10;

-- Business Insight:
-- Tamara Chand is the most profitable customer, contributing 8,981.32 in total profit.
-- Retaining high-profit customers is important because they have a significant impact on overall business profitability.


-- Business Question 25:
-- Show the Top 10 Customers by Number of Orders.

SELECT customer_id,
       customer_name,
       COUNT(DISTINCT order_id) AS Total_Orders
FROM orders
GROUP BY customer_id, customer_name
ORDER BY Total_Orders DESC
LIMIT 10;

-- Business Insight:
-- Emily Phan placed the highest number of unique orders (17).
-- Customers with frequent purchases are valuable because they demonstrate strong engagement and repeat buying behavior.


-- Business Question 26:
-- Which customer segment generated the highest sales?

SELECT segment,
       ROUND(SUM(sales),2) AS Total_Sales
FROM orders
GROUP BY segment
ORDER BY Total_Sales DESC
LIMIT 1;

-- Business Insight:
-- The Consumer segment generated the highest sales, contributing approximately 1.17 million in revenue.
-- This indicates that individual consumers are the company's largest source of sales.



-- Business Question 27:
-- Which customer segment generated the highest profit?

SELECT segment,
       ROUND(SUM(profit),2) AS Total_Profit
FROM orders
GROUP BY segment
ORDER BY Total_Profit DESC
LIMIT 1;

-- Business Insight:
-- The Consumer segment generated the highest profit, contributing approximately 136,371 in total profit.
-- This indicates that the Consumer segment is the company's strongest contributor in terms of both sales and profitability.



-- Business Question 28:
-- Which customers have the highest Average Order Value (Top 10)?

SELECT
    customer_id,
    customer_name,
    ROUND(SUM(sales) / COUNT(DISTINCT order_id), 2) AS Average_Order_Value
FROM orders
GROUP BY customer_id, customer_name
ORDER BY Average_Order_Value DESC
LIMIT 10;

-- Business Insight:
-- Average Order Value (AOV) measures the average amount spent by a customer per order.
-- Customers with a high AOV place fewer but higher-value orders, making them valuable for premium product marketing and personalized sales strategies.
-- These customers can be targeted with exclusive offers, premium memberships, and cross-selling opportunities to maximize revenue.


-- Business Question 29:
-- Which customer segment has the highest Average Order Value?

SELECT
    segment,
    ROUND(SUM(sales) / COUNT(DISTINCT order_id), 2) AS Average_Order_Value
FROM orders
GROUP BY segment
ORDER BY Average_Order_Value DESC
LIMIT 1;

-- Business Insight:
-- The Consumer segment has the highest Average Order Value (445).
-- On average, Consumer customers spend more per order than customers in other segments, making them an attractive segment for premium product offerings and upselling campaigns.



-- Business Question 30:
-- Which year generated the highest sales?

SELECT
    YEAR(order_date) AS Year,
    ROUND(SUM(sales),2) AS Total_Sales
FROM orders
GROUP BY YEAR(order_date)
ORDER BY Total_Sales DESC
LIMIT 1;

-- Business Insight:
-- The year 2026 generated the highest total sales in the dataset.
-- This indicates that business revenue reached its peak during 2026, suggesting strong growth compared to previous years.



-- Business Question 31:
-- Show total sales for each year.

SELECT
    YEAR(order_date) AS Year,
    ROUND(SUM(sales),2) AS Total_Sales
FROM orders
GROUP BY YEAR(order_date)
ORDER BY Total_Sales DESC;

-- Business Insight:
-- Sales increased significantly over the years, with 2026 generating the highest revenue (745,567.53).
-- This trend indicates positive business growth over time, although 2024 recorded lower sales than 2023, suggesting a temporary decline before strong recovery in 2025 and 2026.


-- Business Question 32:
-- Which month generated the highest sales?

SELECT
    MONTHNAME(order_date) AS Month_Name,
    ROUND(SUM(sales),2) AS Total_Sales
FROM orders
GROUP BY MONTHNAME(order_date)
ORDER BY Total_Sales DESC
LIMIT 1;

-- Business Insight:
-- November generated the highest sales (352,665.99).
-- This may indicate strong seasonal demand, festive shopping, or promotional campaigns during November.



-- Business Question 34:
-- Which month generated the highest profit?

SELECT
    MONTHNAME(order_date) AS Month_Name,
    ROUND(SUM(profit),2) AS Total_Profit
FROM orders
GROUP BY MONTHNAME(order_date)
ORDER BY Total_Profit DESC
LIMIT 1;

-- Business Insight:
-- __________ generated the highest profit, contributing __________ in total profit.
-- This indicates that the business earns the highest profitability during this month,
-- making it an important period for maximizing revenue and profit through effective
-- inventory planning, marketing campaigns, and promotional strategies.



-- Business Question 35:
-- Show total profit for all months.

SELECT
    MONTHNAME(order_date) AS Month_Name,
    ROUND(SUM(profit),2) AS Total_Profit
FROM orders
GROUP BY MONTHNAME(order_date)
ORDER BY Total_Profit DESC;

-- Business Insight:
-- The monthly profit analysis highlights the company's most and least profitable months.
-- Identifying profitable months helps management plan inventory, marketing campaigns,
-- and resource allocation more effectively.
-- Comparing monthly sales and profit can also reveal whether high revenue months
-- are equally profitable or are affected by discounts and operating costs.


-- Business Question 36:
-- Which quarter generated the highest sales?

SELECT
    QUARTER(order_date) AS Quarter,
    ROUND(SUM(sales),2) AS Total_Sales
FROM orders
GROUP BY QUARTER(order_date)
ORDER BY Total_Sales DESC
LIMIT 1;

-- Business Insight:
-- Quarter __4___ generated the highest sales in the dataset.
-- This quarter represents the strongest revenue period for the business,
-- indicating increased customer demand and sales performance.




-- Business Question 37:
-- Show total sales for all quarters.

SELECT
    QUARTER(order_date) AS Quarter,
    ROUND(SUM(sales),2) AS Total_Sales
FROM orders
GROUP BY QUARTER(order_date)
ORDER BY Total_Sales DESC;

-- Business Insight:
-- Quarter-wise sales analysis helps identify seasonal business trends.
-- Comparing quarterly performance enables management to evaluate growth,
-- forecast future demand, and optimize business strategies throughout the year.



-- Business Question 38:
-- Which quarter generated the highest profit?

SELECT
    QUARTER(order_date) AS Quarter,
    ROUND(SUM(profit),2) AS Total_Profit
FROM orders
GROUP BY QUARTER(order_date)
ORDER BY Total_Profit DESC
LIMIT 1;

-- Business Insight:
-- Quarter __4___ generated the highest profit in the dataset.
-- This quarter contributed the greatest share of overall profitability,
-- making it a key period for business performance and financial success.
